### ISSUE TITLE
Parser bug

### ISSUE THREAD

**Issue by ghost** [b10011/pyfstab#1]
There is no rule that says comments must start with # at the beginning of a line.
Event the most recent version of `findmnt` (`lt-findmnt from util-linux 2.36.205-97c9e`) has no issues with spaces in front of # when invoked as `sudo findmnt --verify`.
Your `entry.py` contains:
```python
if line and not line[0] == "#":
```
What happens when there is a line in `/etc/fstab` consisting of a space and a `#`?

**Comment by b10011** [comment]
Just to clarify if anyone finds themselves here:

By including one line above the mentioned line, we can see that lines are stripped before testing for `line[0] == "#"`, this way any line with `#` as the first non-whitespace character would be skipped.
```python
line = line.strip()
if line and not line[0] == "#":
```
